export const HOUSING_LIST_REQUEST = 'HOUSING_LIST_REQUEST';
export const HOUSING_LIST_SUCCESS = 'HOUSING_LIST_SUCCESS';
export const HOUSING_LIST_FAIL = 'HOUSING_LIST_FAIL';

export const HOUSING_DETAILS_REQUEST = 'HOUSING_DETAILS_REQUEST';
export const HOUSING_DETAILS_SUCCESS = 'HOUSING_DETAILS_SUCCESS';
export const HOUSING_DETAILS_FAIL = 'HOUSING_DETAILS_FAIL';

export const HOUSING_CREATE_REVIEW_REQUEST = 'HOUSING_CREATE_REVIEW_REQUEST';
export const HOUSING_CREATE_REVIEW_SUCCESS = 'HOUSING_CREATE_REVIEW_SUCCESS';
export const HOUSING_CREATE_REVIEW_FAIL = 'HOUSING_CREATE_REVIEW_FAIL';
export const HOUSING_CREATE_REVIEW_RESET = 'HOUSING_CREATE_REVIEW_RESET';
